name: Naukri Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2,7 * * *" # 08:00 and 13:00 IST
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: Run Script
        env:
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          MOBILE: ${{ secrets.MOBILE }}
          RESUME_DATE_WISE: "true"
        run: python naukri.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: naukri-logs
          path: naukri.log
          retention-days: 30
